version: '3'
services:
  web:
    image: ten7/flightdeck-web-7.4
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html:cached
      - ./db-backups:/var/www/db-backups:cached
      - ./flight-deck.yml:/config/web/flightdeck-web.yml
  db:
    image: ten7/flightdeck-db-10.3
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - /var/lib/mysql
      - ./db-backups:/tmp/db-backups:cached
      - ./flight-deck.yml:/config/mysql/flightdeck-db.yml
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
